/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumenRouteImport } from './routes/resumen'
import { Route as PresupuestoRouteImport } from './routes/presupuesto'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BilleterasRouteImport } from './routes/billeteras'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as ActividadRouteImport } from './routes/actividad'
import { Route as IndexRouteImport } from './routes/index'

const ResumenRoute = ResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoRoute = PresupuestoRouteImport.update({
  id: '/presupuesto',
  path: '/presupuesto',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BilleterasRoute = BilleterasRouteImport.update({
  id: '/billeteras',
  path: '/billeteras',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadRoute = ActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/billeteras': typeof BilleterasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/presupuesto': typeof PresupuestoRoute
  '/resumen': typeof ResumenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/billeteras': typeof BilleterasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/presupuesto': typeof PresupuestoRoute
  '/resumen': typeof ResumenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividad': typeof ActividadRoute
  '/ajustes': typeof AjustesRoute
  '/auth': typeof AuthRoute
  '/billeteras': typeof BilleterasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/presupuesto': typeof PresupuestoRoute
  '/resumen': typeof ResumenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividad'
    | '/ajustes'
    | '/auth'
    | '/billeteras'
    | '/onboarding'
    | '/perfil'
    | '/presupuesto'
    | '/resumen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividad'
    | '/ajustes'
    | '/auth'
    | '/billeteras'
    | '/onboarding'
    | '/perfil'
    | '/presupuesto'
    | '/resumen'
  id:
    | '__root__'
    | '/'
    | '/actividad'
    | '/ajustes'
    | '/auth'
    | '/billeteras'
    | '/onboarding'
    | '/perfil'
    | '/presupuesto'
    | '/resumen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadRoute: typeof ActividadRoute
  AjustesRoute: typeof AjustesRoute
  AuthRoute: typeof AuthRoute
  BilleterasRoute: typeof BilleterasRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PresupuestoRoute: typeof PresupuestoRoute
  ResumenRoute: typeof ResumenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resumen': {
      id: '/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof ResumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto': {
      id: '/presupuesto'
      path: '/presupuesto'
      fullPath: '/presupuesto'
      preLoaderRoute: typeof PresupuestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billeteras': {
      id: '/billeteras'
      path: '/billeteras'
      fullPath: '/billeteras'
      preLoaderRoute: typeof BilleterasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad': {
      id: '/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof ActividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadRoute: ActividadRoute,
  AjustesRoute: AjustesRoute,
  AuthRoute: AuthRoute,
  BilleterasRoute: BilleterasRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PresupuestoRoute: PresupuestoRoute,
  ResumenRoute: ResumenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
